use customer_behaviour;

-- Q1. What is the total revenue generated by male vs. female customers?
select gender, SUM(purchase_amount) as revenue
from mytable
group by gender;

-- Q2. Which customers used a discount but still spent more than the average purchase amount? 
select customer_id, purchase_amount 
from mytable 
where discount_applied = 'Yes' and purchase_amount >= (select AVG(purchase_amount) from mytable);

-- Q3. Which are the top 5 products with the highest average review rating?
select item_purchased, avg(review_rating) as highest_review from mytable 
group by item_purchased 
order by highest_review desc 
limit 5;

-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 
select shipping_type, avg(purchase_amount) from mytable
where shipping_type in ('Express', 'Standard')
group by shipping_type;

-- Q5 Do subscribed customers spend more? Compare average spend and total revenue 
-- between subscribers and non-subscribers.

select subscription_status, count(customer_id) as total_customer, avg(purchase_amount) as avg_spent, sum(purchase_amount) as total_revenue from mytable
group by subscription_status 
order by total_revenue, avg_spent desc;

-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?

select subscription_status, count(customer_id) as repeat_buyer from mytable where  previous_purchases > 5 group by subscription_status;






